//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaudiaIDE.Localized {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResLocalized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLocalized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClaudiaIDE.Localized.ResLocalized", typeof(ResLocalized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image background type.
        /// </summary>
        internal static string BackgroundType {
            get {
                return ResourceManager.GetString("BackgroundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of background image. Single: Displays the specified image. SlideShow: will the image of the specified folder to display slideshow. SingleEach: Displays one different image in the specified folder per opened tab..
        /// </summary>
        internal static string BackgroundTypeDes {
            get {
                return ResourceManager.GetString("BackgroundTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Path.
        /// </summary>
        internal static string DirectoryPathType {
            get {
                return ResourceManager.GetString("DirectoryPathType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image directory path..
        /// </summary>
        internal static string DirectoryPathTypeDes {
            get {
                return ResourceManager.GetString("DirectoryPathTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to IDE.
        /// </summary>
        internal static string ExpandToIDEType {
            get {
                return ResourceManager.GetString("ExpandToIDEType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, background image expand to IDE. If false, background image set to text editor background. (false is default value).
        /// </summary>
        internal static string ExpandToIDETypeDes {
            get {
                return ResourceManager.GetString("ExpandToIDETypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string FilePathType {
            get {
                return ResourceManager.GetString("FilePathType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgroud image file path..
        /// </summary>
        internal static string FilePathTypeDes {
            get {
                return ResourceManager.GetString("FilePathTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Alignment.
        /// </summary>
        internal static string HorizontalAlignmentType {
            get {
                return ResourceManager.GetString("HorizontalAlignmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image position in horizon..
        /// </summary>
        internal static string HorizontalAlignmentTypeDes {
            get {
                return ResourceManager.GetString("HorizontalAlignmentTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image animation interval.
        /// </summary>
        internal static string ImageAnimationIntervalType {
            get {
                return ResourceManager.GetString("ImageAnimationIntervalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image fade animation interval. (value in format: HH:mm:ss).
        /// </summary>
        internal static string ImageAnimationIntervalTypeDes {
            get {
                return ResourceManager.GetString("ImageAnimationIntervalTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image extensions.
        /// </summary>
        internal static string ImageExtensionsType {
            get {
                return ResourceManager.GetString("ImageExtensionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images with this extensions will be shown. (Comma separated).
        /// </summary>
        internal static string ImageExtensionsTypeDes {
            get {
                return ResourceManager.GetString("ImageExtensionsTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Stretch.
        /// </summary>
        internal static string ImageStretchType {
            get {
                return ResourceManager.GetString("ImageStretchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value that specifies how the content of this image stretches to fit the editor. The Image Stretch property accepts the following values: None, Uniform, UniformToFill, Fill.
        /// </summary>
        internal static string ImageStretchTypeDes {
            get {
                return ResourceManager.GetString("ImageStretchTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Slideshow.
        /// </summary>
        internal static string LoopSlideshowType {
            get {
                return ResourceManager.GetString("LoopSlideshowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will cause the slideshow to loop back to the beginning after the last image has been shown..
        /// </summary>
        internal static string LoopSlideshowTypeDes {
            get {
                return ResourceManager.GetString("LoopSlideshowTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Height.
        /// </summary>
        internal static string MaxHeightType {
            get {
                return ResourceManager.GetString("MaxHeightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum height in pixels that the image can fill in the view..
        /// </summary>
        internal static string MaxHeightTypeDes {
            get {
                return ResourceManager.GetString("MaxHeightTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Width.
        /// </summary>
        internal static string MaxWidthType {
            get {
                return ResourceManager.GetString("MaxWidthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum width in pixels that the image can fill in the view..
        /// </summary>
        internal static string MaxWidthTypeDes {
            get {
                return ResourceManager.GetString("MaxWidthTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string OpacityType {
            get {
                return ResourceManager.GetString("OpacityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image opacity. (value within the range of 0.00 &lt;= 1.00).
        /// </summary>
        internal static string OpacityTypeDes {
            get {
                return ResourceManager.GetString("OpacityTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Slideshow.
        /// </summary>
        internal static string ShuffleSlideshowType {
            get {
                return ResourceManager.GetString("ShuffleSlideshowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize the slideshow order..
        /// </summary>
        internal static string ShuffleSlideshowTypeDes {
            get {
                return ResourceManager.GetString("ShuffleSlideshowTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleEach.
        /// </summary>
        internal static string SingleEach {
            get {
                return ResourceManager.GetString("SingleEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleImage.
        /// </summary>
        internal static string SingleImage {
            get {
                return ResourceManager.GetString("SingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlideShow.
        /// </summary>
        internal static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much soft edge applied to background image..
        /// </summary>
        internal static string SoftEdgeDes {
            get {
                return ResourceManager.GetString("SoftEdgeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftEdge Width (X axis).
        /// </summary>
        internal static string SoftEdgeX {
            get {
                return ResourceManager.GetString("SoftEdgeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftEdge Width (Y axis).
        /// </summary>
        internal static string SoftEdgeY {
            get {
                return ResourceManager.GetString("SoftEdgeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval.
        /// </summary>
        internal static string UpdateIntervalType {
            get {
                return ResourceManager.GetString("UpdateIntervalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image change interval. (value in format: HH:mm:ss).
        /// </summary>
        internal static string UpdateIntervalTypeDes {
            get {
                return ResourceManager.GetString("UpdateIntervalTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Alignment.
        /// </summary>
        internal static string VerticalAlignmentType {
            get {
                return ResourceManager.GetString("VerticalAlignmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image position in vertical..
        /// </summary>
        internal static string VerticalAlignmentTypeDes {
            get {
                return ResourceManager.GetString("VerticalAlignmentTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image horizontal position in ViewBox.
        /// </summary>
        internal static string ViewBoxPointX {
            get {
                return ResourceManager.GetString("ViewBoxPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property can set a double value for the Image horizontal position in WPF ViewBox..
        /// </summary>
        internal static string ViewBoxPointXDes {
            get {
                return ResourceManager.GetString("ViewBoxPointXDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image vertical position in ViewBox.
        /// </summary>
        internal static string ViewBoxPointY {
            get {
                return ResourceManager.GetString("ViewBoxPointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property can set double value about Image vertical position in WPF ViewBox..
        /// </summary>
        internal static string ViewBoxPointYDes {
            get {
                return ResourceManager.GetString("ViewBoxPointYDes", resourceCulture);
            }
        }
    }
}
