//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaudiaIDE.Localized {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResLocalized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLocalized() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClaudiaIDE.Localized.ResLocalized", typeof(ResLocalized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Image background type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BackgroundType {
            get {
                return ResourceManager.GetString("BackgroundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Types of background image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BackgroundTypeDes {
            get {
                return ResourceManager.GetString("BackgroundTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryPathType {
            get {
                return ResourceManager.GetString("DirectoryPathType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background image directory path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryPathTypeDes {
            get {
                return ResourceManager.GetString("DirectoryPathTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilePathType {
            get {
                return ResourceManager.GetString("FilePathType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backgroud image file path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilePathTypeDes {
            get {
                return ResourceManager.GetString("FilePathTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal Alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HorizontalAlignmentType {
            get {
                return ResourceManager.GetString("HorizontalAlignmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image position in horizon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HorizontalAlignmentTypeDes {
            get {
                return ResourceManager.GetString("HorizontalAlignmentTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image animation interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageAnimationIntervalType {
            get {
                return ResourceManager.GetString("ImageAnimationIntervalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background image fade animation interval. (value in format: HH:mm:ss) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageAnimationIntervalTypeDes {
            get {
                return ResourceManager.GetString("ImageAnimationIntervalTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageExtensionsType {
            get {
                return ResourceManager.GetString("ImageExtensionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only images with this extensions will be shown. (Comma separated) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageExtensionsTypeDes {
            get {
                return ResourceManager.GetString("ImageExtensionsTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Stretch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageStretchType {
            get {
                return ResourceManager.GetString("ImageStretchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A value that specifies how the content of this image stretches to fit the editor. The Image Stretch property accepts the following values: None, Uniform, UniformToFill, Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageStretchTypeDes {
            get {
                return ResourceManager.GetString("ImageStretchTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loop Slideshow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoopSlideshowType {
            get {
                return ResourceManager.GetString("LoopSlideshowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will cause the slideshow to loop back to the beginning after the last image has been shown. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoopSlideshowTypeDes {
            get {
                return ResourceManager.GetString("LoopSlideshowTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxHeightType {
            get {
                return ResourceManager.GetString("MaxHeightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum height in pixels that the image can fill in the view. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxHeightTypeDes {
            get {
                return ResourceManager.GetString("MaxHeightTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxWidthType {
            get {
                return ResourceManager.GetString("MaxWidthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum width in pixels that the image can fill in the view. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxWidthTypeDes {
            get {
                return ResourceManager.GetString("MaxWidthTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpacityType {
            get {
                return ResourceManager.GetString("OpacityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background image opacity. (value within the range of 0.00 &lt;= 1.00) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpacityTypeDes {
            get {
                return ResourceManager.GetString("OpacityTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SingleImage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SingleImage {
            get {
                return ResourceManager.GetString("SingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SlideShow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateIntervalType {
            get {
                return ResourceManager.GetString("UpdateIntervalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background image change interval. (value in format: HH:mm:ss) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateIntervalTypeDes {
            get {
                return ResourceManager.GetString("UpdateIntervalTypeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical Alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VerticalAlignmentType {
            get {
                return ResourceManager.GetString("VerticalAlignmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image position in vertical. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VerticalAlignmentTypeDes {
            get {
                return ResourceManager.GetString("VerticalAlignmentTypeDes", resourceCulture);
            }
        }
    }
}
